### PR TITLE
CHROM-85: Add AAC to ACM

### PR DESCRIPTION
**Pull request by digitalmouse12**
//cc: @willkelleher 

Notes:
- The first commit contains a `AacWindowsEncoder` and `AacWindowsDecoder` class. I eventually plan on creating a base class from which these are both derived. But in the interest of time, I've separated them into two classes.
- I first wrte Windows implementations for AAC encoding/decoding. Then I wrote webrtc wrappers and inserted the AAC codec into their database.
- I didn't write unit tests

@jstys92 would love some extra eyes on this. If you have time, can you scan this over and check basic logic and wrapping?

### CODE REVIEW

**Comment by digitalmouse12** [comment]
Addressed @jstys92's alignment/free comments

**Comment by jstys92** [comment]
:+1:

**Comment by willkelleher** [comment]
I've tested this, it worked well for me (on the send side). Not too picky about the details :+1:

**Comment by digitalmouse12** [comment]
Going to close this and make a new PR on top of `develop`

**Pull request closed without merging**
