### PR TITLE
BOSH: Add locking around queue operations, stanza processing fix 

### PR DESCRIPTION
**Pull request by dscherba**
- Certain termination flows (e.g. signout) hit this codepath

### CODE REVIEW

**Comment by dscherba** [comment]
JIRA tracker TBD, so may want to hold-off on this. Corresponds to NE-044.

//cc @digitalmouse12 @DinhNguyenCat

**Comment by digitalmouse12** [comment]
:+1:

**Comment by longk15t** [comment]
Tracked in https://personify.atlassian.net/browse/CHAT-2386

**Comment by DinhNguyenCat** [comment]
I guess that you found the issue that there are 2 sockets were trying to read the queue at the same time, and the second one crashed due to the output queue is empty?
If yes, then I think the new code will not completely fix the issue, there is the same check about 4 lines above this check.
In my opinion, in this case the best solution is using a lock to avoid race condition. I tried not to use this in my original implementation but seem like there are problems left, I'm sorry for that.
Beside, with the current fix, in stead of adding new check, how about moving all the code below the first check into an "else". 
The current code will make a confusion since there are 2 same checks for output_queue in one function. And we still did not modify the output_queue yet.

**Comment by dscherba** [comment]
Good points... and yes, it sounds like locking is needed here.

**Comment by dscherba** [comment]
@digitalmouse12 , @DinhNguyenCat : updated with more correct synchronization (locking around XMPP queue access). 

Also fixed a bug in the BOSH received stanza processing in the case of fragmented messages. I think this might have been related to some of the customer failures... one of those "I'm not actually sure how this [ever] worked" sort of things ;-)... it probably mostly worked because fragmented messages are rare.

**Comment by DinhNguyenCat** [comment]
:+1: LGTM

**Comment by dscherba** [comment]
Merging.

**Pull request merged**
